import {
  MenuIcon,
  SearchIcon,
  ShoppingCartIcon,
} from "@heroicons/react/outline";
import Head from "next/head";

import type { NextPage } from "next";
import Logo from "../src/components/Logo";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-200 py-5 text-center text-xs">
        <div className="font-bold">NOTICE</div>
        <div>로그인이 어려우실 경우 FAQ를 참조해주세요.</div>
      </div>
      <header className="relative flex justify-between border-b p-3">
        <Logo className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
        <button>
          <MenuIcon className="w-6" />
        </button>
        <div className="flex space-x-3">
          <button className="relative">
            <ShoppingCartIcon className="w-6" />
            <div className="absolute top-0 right-0 flex h-4 w-4 translate-x-1/3 -translate-y-1/3 items-center justify-center rounded-full bg-green-400">
              <span className="text-[0.7rem] text-white">0</span>
            </div>
          </button>
          <button>
            <SearchIcon className="w-6" />
          </button>
        </div>
      </header>
    </>
  );
};
export default Home;