import {
  HeartIcon,
  MenuIcon,
  QuestionMarkCircleIcon,
  SearchIcon,
  ShoppingCartIcon,
  UserIcon,
} from "@heroicons/react/outline";
import Head from "next/head";

import type { NextPage } from "next";
import Logo from "../src/components/Logo";
import Header from "../src/components/Header";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-200 py-5 text-center text-xs">
        <div className="font-bold">NOTICE</div>
        <div>로그인이 어려우실 경우 FAQ를 참조해주세요.</div>
      </div>
<Header>
</Header>
    </>
  );
};
export default Home;