/* eslint-disable @next/next/no-img-element */
import {
  ArrowRightIcon,
  HeartIcon,
  MenuIcon,
  QuestionMarkCircleIcon,
  SearchIcon,
  ShoppingCartIcon,
  UserIcon,
} from "@heroicons/react/outline";
import Head from "next/head";

import type { NextPage } from "next";
import Logo from "../src/components/Logo";
import Header from "../src/components/Header";
import HeroButton from "../src/components/HeroButton";
import Button from "../src/components/Button";

import shopImage1 from "../public/images/shop-1.jpeg";
import shopImage2 from "../public/images/shop-2.jpeg";
import shopImage3 from "../public/images/shop-3.jpeg";
import shopImage4 from "../public/images/shop-4.jpeg";

const shopImages = [shopImage1, shopImage2, shopImage3, shopImage4];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-200 py-5 text-center text-xs">
        <div className="font-bold">NOTICE</div>
        <div>로그인이 어려우실 경우 FAQ를 참조해주세요.</div>
      </div>
      <Header />
      <main className="max-w-8xl mx-auto w-full">
        <section>
          <div className="relative w-full">
            <img
              src="./images/hero-1.jpeg"
              alt="background image for hero section"
              className="w-full md:hidden"
            />
            <img
              src="./images/hero-2.jpeg"
              alt="background image for hero section"
              className="hidden w-full md:block"
            />
            <div className="top-10 left-10 hidden md:absolute md:block">
              <h2 className="text-3xl font-medium uppercase leading-8 text-white lg:leading-[3rem] xl:text-5xl xl:leading-[4rem]">
                chuck 70
                <br />
                seaseonal color
              </h2>
              <p className="mt-4 text-sm text-white lg:text-base">
                아카이브 컬러의 프리미엄 재활용 캔버스로 지구를 생각하는 마음을
                당믄 최고의 척 70.
              </p>
              <Button isMobile={false} className="mt-5">
                더 알아보기
              </Button>
            </div>
            <div className="flex flex-col items-center justify-center space-y-6 bg-black py-20 px-24 md:hidden">
              <h2 className="text-center text-3xl font-medium uppercase leading-8 text-white lg:text-4xl lg:leading-[3rem] xl:text-5xl xl:leading-[4rem]">
                chuck 70
                <br />
                seasonal color
              </h2>
              <p className="text-xs font-medium leading-5 text-white">
                아카이브 컬러의 프리미엄 재활용 캔버스로
                <br />
                지구를 생각하는 마음을 담은 최고의 척 70.
              </p>
              <Button>더 알아보기</Button>
            </div>
          </div>
        </section>

        <section className="space-y-4 pt-10">
          <div className="space-y-2 px-4">
            <h3 className="text-2xl font-medium md:text-3xl">Shop By Style</h3>
            <a
              href="#"
              className="flex w-max items-center space-x-2 hover:underline hover:opacity-70"
            >
              <ArrowRightIcon className="w-5" />
              <span>신상품 보러 가기</span>
            </a>
          </div>
          <div className="flex overflow-x-auto">
            {shopImages.map((image, idx) => (
              <a
                href="#"
                key={`image-${idx}`}
                className="transition-opacity hover:opacity-70"
              >
                <div className="w-56 md:w-full">
                  <img src={image.src} alt="converse image" />
                </div>
              </a>
            ))}
          </div>
        </section>
      </main>
    </>
  );
};
export default Home;
